export const strings = {
  en: {
    // ── Navbar ──────────────────────────────────────────────────────────────
    nav_auctions: 'Auctions',
    nav_collections: 'Collections',
    nav_provenance: 'Provenance',
    nav_how_it_works: 'How it works',
    nav_sign_in: 'Sign in',
    nav_start_bidding: 'Start bidding',
    nav_sell: 'Sell',
    nav_watchlist: 'Watchlist',
    nav_profile: 'Profile Settings',
    nav_admin: 'Admin Console',
    nav_create_listing: 'Create Listing',
    nav_logout: 'Log out',
    nav_search_placeholder: 'Search collections...',

    // ── HomePage — Hero ──────────────────────────────────────────────────────
    hero_eyebrow: "Cairo, Egypt • EST. 2026 • MENA'S RARE AUCTION HOUSE",
    hero_headline: 'Where rare things find their place.',
    hero_subheadline: 'A curated digital sanctuary for objects of historical significance and enduring value.',
    hero_search_placeholder: 'Search rare collections...',
    hero_search_button: 'Search',

    // ── HomePage — LiveHero card ─────────────────────────────────────────────
    hero_current_bid: 'Current Bid',
    hero_time_remaining: 'Time Remaining',
    hero_place_bid: 'Place bid',
    hero_view_lot: 'View lot',
    hero_bidders_active: 'Bidders Active',
    hero_last_bid: 'Last Bid: Anonymous Bidder',

    // ── HomePage — Live Ticker ───────────────────────────────────────────────
    ticker_label: 'Live Bids',
    ticker_just_now: 'Just now',

    // ── HomePage — Recently Sold marquee ────────────────────────────────────
    marquee_label: 'Recently Sold',
    marquee_sold_for: 'Sold for',
    marquee_empty: 'The archives are currently being curated... Check back soon for recently sold lots.',

    // ── HomePage — Departments section ──────────────────────────────────────
    departments_eyebrow: 'Specialized Departments',
    departments_heading: 'Explore by Department',

    // ── HomePage — Features section ─────────────────────────────────────────
    feature_ai_title: 'AI-Secured Bidding',
    feature_ai_desc: 'Our neural networks detect and block fraudulent bidding patterns in real-time.',
    feature_global_title: 'Global Authenticity',
    feature_global_desc: 'Every listing is verified by our network of category experts across the globe.',
    feature_live_title: 'Live Synchronization',
    feature_live_desc: 'Experience zero-latency bidding with our real-time synchronization engine.',

    // ── HomePage — How It Works ──────────────────────────────────────────────
    how_heading: 'Master the Auction',
    how_subheading: 'Join thousands of collectors in three simple steps.',
    how_step1_title: 'Create Account',
    how_step1_desc: 'Join the community and get verified to start your journey.',
    how_step2_title: 'Place Bids',
    how_step2_desc: 'Find your treasure and use our real-time engine to stay ahead.',
    how_step3_title: 'Win & Collect',
    how_step3_desc: 'Complete your payment securely and receive your item.',

    // ── HomePage — Section headers ───────────────────────────────────────────
    section_ending_soon: 'Ending Soon',
    section_opening_soon: 'Opening Soon',
    section_live_auctions: 'Live Auctions',
    section_explore_all: 'Explore all listings',

    // ── HomePage — CTA section ───────────────────────────────────────────────
    cta_eyebrow: '◆ Provenance & Partnership ◆',
    cta_heading: 'Possess an Object of Distinction?',
    cta_body: "Entrust your masterpieces to MENA's premier curated digital auction house. Connect directly with verified global collectors, supported by real-time neural fraud protection and zero-latency transaction verification.",
    cta_button: 'Consign Your Collection',

    // ── HomePage — Empty states ──────────────────────────────────────────────
    empty_category: 'No active auctions in',
    empty_reset: 'Reset filters',

    // ── AuctionCard ──────────────────────────────────────────────────────────
    card_live: 'Live',
    card_current_bid: 'Current Bid',
    card_bids: 'bids',
    card_watching: 'watching',

    // ── AuctionDetailPage ────────────────────────────────────────────────────
    detail_back: 'Back to directory',
    detail_current_bid_status: 'Current Bid Status',
    detail_time_remaining: 'Time Remaining',
    detail_starts_in: 'Starts In',
    detail_bids_logged: 'Bids Logged',
    detail_opening_price: 'Opening Price',
    detail_reserve_met: 'Reserve Met',
    detail_reserve_not_met: 'Reserve Not Met',
    detail_people_watching: 'people watching',
    detail_bids_last_hour: 'bids in the last hour',
    detail_lot_description: 'Lot Description & Specifications',
    detail_listed_by: 'Listed By Curator',
    detail_curator_rating: 'Curator Rating',
    detail_upcoming_title: 'Upcoming Auction',
    detail_upcoming_desc: 'This lot will be open for bidding soon.',
    detail_browse_open: 'Browse open lots',
    detail_auction_closed: 'Auction Closed',
    detail_hammer_price: 'Hammer Price — Lot Sold',
    detail_reserve_unsold: 'Reserve Not Met — Lot Unsold',
    detail_lot_won: 'Lot Won!',
    detail_lot_closed: 'Lot Closed',
    detail_sold_for: 'Sold for',
    detail_unsold: 'Unsold - Reserve Not Met',
    detail_congrats: 'Congratulations, you won this lot!',
    detail_final_price: 'Final Price',
    detail_complete_payment: 'Complete Payment',
    detail_payment_completed: 'Payment Completed',
    detail_admin_controls: 'Admin controls',
    detail_edit_listing: 'Edit Listing',
    detail_delete_lot: 'Delete Lot',
    detail_return: 'Return to directory',
    detail_not_found: 'Archival listing not found',
    detail_secure_payment: 'Secure payment integration via Stripe',
    detail_you_won: 'You won this archival lot!',
    detail_complete_checkout: 'Complete Checkout Now',
    detail_lot_paid: 'Archival Lot Paid',
    detail_payment_confirmed: 'Payment confirmed.',
    detail_winner_banner_congrats: 'Congratulations, you won this lot!',
    detail_anti_snipe_title: '⚡ ANTI-SNIPE ACTIVE',
    detail_anti_snipe_desc: 'Auction extended to prevent last-second sniping',

    // ── AI Market Insight panel ──────────────────────────────────────────────
    ai_insight_title: 'AI Market Insight',
    ai_insight_est_value: 'Estimated Market Value',
    ai_insight_demand: 'Demand Trend',
    ai_insight_velocity: 'Bid Velocity',
    ai_insight_fraud_risk: 'Fraud Risk',

    // ── SearchPage ───────────────────────────────────────────────────────────
    search_heading: 'Search Archival Lots',
    search_placeholder: 'Search by title, description, provenance…',
    search_button: 'Search',
    search_all_statuses: 'All Statuses',
    search_live: 'Live Auctions',
    search_ending_soon: 'Ending Soon',
    search_upcoming: 'Upcoming Auctions',
    search_price_high: 'Price: High to Low',
    search_price_low: 'Price: Low to High',
    search_newest: 'Newest Listed',
    search_ending_soonest: 'Ending Soonest',
    search_most_bids: 'Most Bids',
    search_min_price: 'Min price',
    search_max_price: 'Max price',
    search_clear_filters: 'Clear Filters',
    search_retrieving: 'Retrieving listings…',
    search_lots_found: 'lots found',
    search_for: 'for',
    search_empty_title: 'No archival lots found',
    search_empty_desc: 'Try adjusting keywords or price thresholds',
    search_clear_all: 'Clear All Filters',
    search_page_of: 'Page',
    search_of: 'of',
    search_previous: 'Previous',
    search_next: 'Next',

    // ── LoginPage ────────────────────────────────────────────────────────────
    login_welcome: 'Welcome Back',
    login_subtitle: 'Sign in to your archival account',
    login_email_label: 'Email Address',
    login_email_placeholder: 'name@archival.com',
    login_password_label: 'Password',
    login_forgot: 'Forgot?',
    login_button: 'Sign In',
    login_loading: 'Accessing Sanctuary…',
    login_no_account: "Don't have an account?",
    login_create: 'Create One',
    login_back: 'Back to Home',

    // ── AdminPage ────────────────────────────────────────────────────────────
    admin_heading: 'Registry Command',
    admin_subtitle: 'Platform monitoring, fraud assessment, and user controls',
    admin_tab_overview: 'Overview',
    admin_tab_fraud: 'Fraud queue',
    admin_tab_users: 'Users',
    admin_tab_activity: 'Activity',
    admin_pending_flags: 'pending fraud flags',
    admin_pending_flag: 'pending fraud flag',
    admin_kpi_bids: 'Bids Placed Today',
    admin_kpi_active: 'Active Listings',
    admin_kpi_fraud: 'Fraud Flagged',
    admin_kpi_bots: 'Bots Repelled',
    admin_integrity_title: 'Bidding Integrity Breakdown',
    admin_volume_title: 'Bid Volume — Last 24 Hours',
    admin_ab_title: 'A/B Experiments — Recommendation Engine',
    admin_security_flags: 'Recent Security Flags',
    admin_bot_blocks: 'Recent Bot Blocks',
    admin_view_queue: 'View queue',
    admin_fraud_clear: 'Security Queue Clear',
    admin_fraud_clear_sub: 'All incoming platform bids are classified clean',
    admin_user_identity: 'User Identity',
    admin_user_status: 'Registry Status',
    admin_user_joined: 'Joined',
    admin_user_actions: 'Actions',
    admin_ban: 'Ban',
    admin_unban: 'Unban',
    admin_no_activity: 'No Recent Activity',
    admin_event: 'Archival Event',
    admin_event_time: 'Registered Time',
    admin_system_status: 'System Service Status',
    admin_allow: 'Allow',
    admin_escalate: 'Escalate',
  },

  ar: {
    // ── Navbar ──────────────────────────────────────────────────────────────
    nav_auctions: 'المزادات',
    nav_collections: 'المجموعات',
    nav_provenance: 'المصدر',
    nav_how_it_works: 'كيف تعمل',
    nav_sign_in: 'تسجيل الدخول',
    nav_start_bidding: 'ابدأ المزايدة',
    nav_sell: 'بيع',
    nav_watchlist: 'قائمة المتابعة',
    nav_profile: 'إعدادات الملف',
    nav_admin: 'لوحة الإدارة',
    nav_create_listing: 'إنشاء قائمة',
    nav_logout: 'تسجيل الخروج',
    nav_search_placeholder: 'ابحث في المجموعات...',

    // ── HomePage — Hero ──────────────────────────────────────────────────────
    hero_eyebrow: 'القاهرة، مصر • تأسست ٢٠٢٦ • دار مزاد منطقة الشرق الأوسط وشمال أفريقيا',
    hero_headline: 'حيث تجد الأشياء النادرة مكانها.',
    hero_subheadline: 'ملاذ رقمي مُنتقى للقطع ذات الأهمية التاريخية والقيمة الدائمة.',
    hero_search_placeholder: 'ابحث في المجموعات النادرة...',
    hero_search_button: 'بحث',

    // ── HomePage — LiveHero card ─────────────────────────────────────────────
    hero_current_bid: 'العرض الحالي',
    hero_time_remaining: 'الوقت المتبقي',
    hero_place_bid: 'قدّم عرضاً',
    hero_view_lot: 'عرض القطعة',
    hero_bidders_active: 'مزايد نشط',
    hero_last_bid: 'آخر عرض: مزايد مجهول',

    // ── HomePage — Live Ticker ───────────────────────────────────────────────
    ticker_label: 'مزايدات مباشرة',
    ticker_just_now: 'الآن',

    // ── HomePage — Recently Sold marquee ────────────────────────────────────
    marquee_label: 'بيعت مؤخراً',
    marquee_sold_for: 'بيعت بـ',
    marquee_empty: 'جاري تنظيم الأرشيف... تفقّد قريباً للاطلاع على القطع المباعة.',

    // ── HomePage — Departments section ──────────────────────────────────────
    departments_eyebrow: 'أقسام متخصصة',
    departments_heading: 'استكشف حسب القسم',

    // ── HomePage — Features section ─────────────────────────────────────────
    feature_ai_title: 'مزايدة محمية بالذكاء الاصطناعي',
    feature_ai_desc: 'تكتشف شبكاتنا العصبية أنماط المزايدة الاحتيالية وتحجبها في الوقت الفعلي.',
    feature_global_title: 'مصداقية عالمية',
    feature_global_desc: 'تُوثَّق كل قائمة بمعرفة شبكة من الخبراء المتخصصين حول العالم.',
    feature_live_title: 'مزامنة فورية',
    feature_live_desc: 'استمتع بتجربة مزايدة بدون أي تأخير عبر محرك المزامنة الفورية.',

    // ── HomePage — How It Works ──────────────────────────────────────────────
    how_heading: 'أتقن فن المزاد',
    how_subheading: 'انضم إلى آلاف الهواة في ثلاث خطوات بسيطة.',
    how_step1_title: 'إنشاء حساب',
    how_step1_desc: 'انضم إلى المجتمع واحصل على التحقق لبدء رحلتك.',
    how_step2_title: 'قدّم عروضاً',
    how_step2_desc: 'اعثر على كنزك واستخدم محرك الوقت الفعلي للبقاء في المقدمة.',
    how_step3_title: 'اربح واقتنِ',
    how_step3_desc: 'أتمّ دفعتك بأمان واستلم قطعتك.',

    // ── HomePage — Section headers ───────────────────────────────────────────
    section_ending_soon: 'تنتهي قريباً',
    section_opening_soon: 'تبدأ قريباً',
    section_live_auctions: 'المزادات المباشرة',
    section_explore_all: 'استعراض جميع القطع',

    // ── HomePage — CTA section ───────────────────────────────────────────────
    cta_eyebrow: '◆ الأصالة والشراكة ◆',
    cta_heading: 'هل تمتلك قطعة استثنائية؟',
    cta_body: 'عهِّد بروائعك إلى أبرز دور المزادات الرقمية المنتقاة في منطقة الشرق الأوسط وشمال أفريقيا. تواصل مباشرةً مع هواة الاقتناء الموثَّقين حول العالم، بدعم من الحماية العصبية الفورية ضد الاحتيال.',
    cta_button: 'أودِع مجموعتك',

    // ── HomePage — Empty states ──────────────────────────────────────────────
    empty_category: 'لا توجد مزادات نشطة في',
    empty_reset: 'إعادة ضبط الفلاتر',

    // ── AuctionCard ──────────────────────────────────────────────────────────
    card_live: 'مباشر',
    card_current_bid: 'العرض الحالي',
    card_bids: 'عرض',
    card_watching: 'يتابع',

    // ── AuctionDetailPage ────────────────────────────────────────────────────
    detail_back: 'العودة إلى الدليل',
    detail_current_bid_status: 'حالة العرض الحالي',
    detail_time_remaining: 'الوقت المتبقي',
    detail_starts_in: 'يبدأ خلال',
    detail_bids_logged: 'عرض مسجّل',
    detail_opening_price: 'سعر الافتتاح',
    detail_reserve_met: 'تم الوصول للسعر المحفوظ',
    detail_reserve_not_met: 'لم يُستوفَ السعر المحفوظ',
    detail_people_watching: 'شخص يتابع',
    detail_bids_last_hour: 'عرض في الساعة الأخيرة',
    detail_lot_description: 'وصف القطعة والمواصفات',
    detail_listed_by: 'قائمة بواسطة المنسِّق',
    detail_curator_rating: 'تقييم المنسِّق',
    detail_upcoming_title: 'مزاد قادم',
    detail_upcoming_desc: 'ستُفتح هذه القطعة للمزايدة قريباً.',
    detail_browse_open: 'تصفّح القطع المتاحة',
    detail_auction_closed: 'انتهى المزاد',
    detail_hammer_price: 'سعر المطرقة — بيعت القطعة',
    detail_reserve_unsold: 'لم يُستوفَ السعر المحفوظ — لم تُبَع القطعة',
    detail_lot_won: 'فزت بالقطعة!',
    detail_lot_closed: 'أُغلقت القطعة',
    detail_sold_for: 'بيعت بـ',
    detail_unsold: 'لم تُبَع - لم يُستوفَ السعر المحفوظ',
    detail_congrats: 'تهانينا، لقد فزت بهذه القطعة!',
    detail_final_price: 'السعر النهائي',
    detail_complete_payment: 'إتمام الدفع',
    detail_payment_completed: 'تم الدفع',
    detail_admin_controls: 'أدوات الإدارة',
    detail_edit_listing: 'تعديل القائمة',
    detail_delete_lot: 'حذف القطعة',
    detail_return: 'العودة إلى الدليل',
    detail_not_found: 'لم يُعثر على القطعة الأرشيفية',
    detail_secure_payment: 'دفع آمن عبر Stripe',
    detail_you_won: 'لقد فزت بهذه القطعة الأرشيفية!',
    detail_complete_checkout: 'إتمام الدفع الآن',
    detail_lot_paid: 'تم دفع القطعة الأرشيفية',
    detail_payment_confirmed: 'تم تأكيد الدفع.',
    detail_winner_banner_congrats: 'تهانينا، لقد فزت بهذه القطعة!',
    detail_anti_snipe_title: '⚡ نظام الحماية من القنص مفعّل',
    detail_anti_snipe_desc: 'تم تمديد المزاد للحماية من المزايدة في اللحظة الأخيرة',

    // ── AI Market Insight panel ──────────────────────────────────────────────
    ai_insight_title: 'تقييم السوق بالذكاء الاصطناعي',
    ai_insight_est_value: 'القيمة السوقية التقديرية',
    ai_insight_demand: 'اتجاه الطلب',
    ai_insight_velocity: 'سرعة العروض',
    ai_insight_fraud_risk: 'مخاطر الاحتيال',

    // ── SearchPage ───────────────────────────────────────────────────────────
    search_heading: 'البحث في القطع الأرشيفية',
    search_placeholder: 'ابحث بالعنوان أو الوصف أو المصدر...',
    search_button: 'بحث',
    search_all_statuses: 'جميع الحالات',
    search_live: 'مزادات مباشرة',
    search_ending_soon: 'تنتهي قريباً',
    search_upcoming: 'مزادات قادمة',
    search_price_high: 'السعر: من الأعلى',
    search_price_low: 'السعر: من الأدنى',
    search_newest: 'الأحدث إدراجاً',
    search_ending_soonest: 'الأقرب انتهاءً',
    search_most_bids: 'الأكثر عروضاً',
    search_min_price: 'أدنى سعر',
    search_max_price: 'أعلى سعر',
    search_clear_filters: 'مسح الفلاتر',
    search_retrieving: 'جاري استرداد القطع...',
    search_lots_found: 'قطعة موجودة',
    search_for: 'لـ',
    search_empty_title: 'لم يُعثر على قطع أرشيفية',
    search_empty_desc: 'حاول تعديل الكلمات المفتاحية أو حدود السعر',
    search_clear_all: 'مسح جميع الفلاتر',
    search_page_of: 'صفحة',
    search_of: 'من',
    search_previous: 'السابق',
    search_next: 'التالي',

    // ── LoginPage ────────────────────────────────────────────────────────────
    login_welcome: 'مرحباً بعودتك',
    login_subtitle: 'سجّل الدخول إلى حسابك الأرشيفي',
    login_email_label: 'البريد الإلكتروني',
    login_email_placeholder: 'name@archival.com',
    login_password_label: 'كلمة المرور',
    login_forgot: 'نسيت؟',
    login_button: 'تسجيل الدخول',
    login_loading: 'جاري الوصول...',
    login_no_account: 'ليس لديك حساب؟',
    login_create: 'أنشئ حساباً',
    login_back: 'العودة للرئيسية',

    // ── AdminPage ────────────────────────────────────────────────────────────
    admin_heading: 'مركز التحكم',
    admin_subtitle: 'مراقبة المنصة وتقييم الاحتيال وإدارة المستخدمين',
    admin_tab_overview: 'نظرة عامة',
    admin_tab_fraud: 'طابور الاحتيال',
    admin_tab_users: 'المستخدمون',
    admin_tab_activity: 'النشاط',
    admin_pending_flags: 'إشارة احتيال معلّقة',
    admin_pending_flag: 'إشارة احتيال معلّقة',
    admin_kpi_bids: 'العروض المقدّمة اليوم',
    admin_kpi_active: 'القطع النشطة',
    admin_kpi_fraud: 'مشبوهو الاحتيال',
    admin_kpi_bots: 'روبوتات مُعترَضة',
    admin_integrity_title: 'تحليل نزاهة المزايدة',
    admin_volume_title: 'حجم العروض — آخر ٢٤ ساعة',
    admin_ab_title: 'تجارب أ/ب — محرك التوصيات',
    admin_security_flags: 'إشارات الأمان الأخيرة',
    admin_bot_blocks: 'عمليات حجب الروبوتات الأخيرة',
    admin_view_queue: 'عرض الطابور',
    admin_fraud_clear: 'طابور الأمان نظيف',
    admin_fraud_clear_sub: 'جميع العروض الواردة إلى المنصة مصنّفة نظيفة',
    admin_user_identity: 'هوية المستخدم',
    admin_user_status: 'حالة التسجيل',
    admin_user_joined: 'تاريخ الانضمام',
    admin_user_actions: 'الإجراءات',
    admin_ban: 'حظر',
    admin_unban: 'رفع الحظر',
    admin_no_activity: 'لا يوجد نشاط حديث',
    admin_event: 'حدث أرشيفي',
    admin_event_time: 'وقت التسجيل',
    admin_system_status: 'حالة خدمات النظام',
    admin_allow: 'سماح',
    admin_escalate: 'تصعيد',
  },
}

export type Strings = typeof strings.en
